"""Physical intent. The spec already knows which nets are PCIe pairs and how many amps each rail carries;
add one Fab object and the layout constraints fall out. Output: a table, and a KiCad custom-rules file."""
from .units import *
from .core import K, DIFF

OZ=um(34.8)                                                   # 1 oz/ft2 copper
class Fab:
    def __init__(s,name,layers,thickness,cu_outer_oz=1.0,cu_inner_oz=0.5,min_track=mm(0.1),min_space=mm(0.1),
                 dT=degC(10),plane_above=mm(1.5),diff=None,hs_layers=("F.Cu",),hs_max_vias=0,skew=mil(5),verified=False,hs_exceptions=None):
        s.name,s.layers,s.thickness,s.cu_outer_oz,s.cu_inner_oz,s.min_track,s.min_space=name,layers,thickness,cu_outer_oz,cu_inner_oz,min_track,min_space
        s.dT,s.plane_above,s.hs_layers,s.hs_max_vias,s.skew,s.verified=dT,plane_above,hs_layers,hs_max_vias,skew,verified
        s.diff=diff or {}                                     # discipline -> (width, gap, ohms). ONLY from the fab's impedance calculator.
        s.hs_exceptions=hs_exceptions or {}                   # text found in a pair's name -> (layers, max vias), where the default cannot hold
    def limits(s,pair_name):
        """(allowed layers, max vias per trace) for one pair: the first exception whose key occurs in the name, else the default."""
        return next((v for k,v in s.hs_exceptions.items() if k in pair_name),(s.hs_layers,s.hs_max_vias))

def ipc2221_width(I,oz=1.0,dT=degC(10),external=True):
    """IPC-2221: I = k * dT^0.44 * A^0.725, A in mil^2. Conservative; fine for a first pass."""
    kk=0.048 if external else 0.024
    area=(float(I)/(kk*float(dT)**0.44))**(1/0.725)
    return mil(area/(1.378*oz))

class Rail:
    def __init__(s,net,I,width,plane): s.net,s.I,s.width,s.plane=net,I,width,plane
class Pair:
    def __init__(s,name,p,n,disc,geom,layers=("F.Cu",),max_vias=0): s.name,s.p,s.n,s.disc,s.geom,s.layers,s.max_vias=name,p,n,disc,geom,tuple(layers),max_vias

def constraints(c,fab,W):
    """Run after check() and derive(). Returns (rails, pairs)."""
    rails,pairs=[],[]
    for n in c.nets.values():
        if n.disc=="rail" and n.ipk is not None and n.ipk>0:
            w=max(ipc2221_width(n.ipk,fab.cu_outer_oz,fab.dT),fab.min_track)
            rails.append(Rail(n.name,n.ipk,w,w>fab.plane_above))
    seen={}
    for n in c.nets.values():
        d=[p for p in n.pins if p.kind in DIFF]
        if d: seen.setdefault((d[0].part.ref,d[0].kind,d[0].lane),{})[d[0].pol]=n
    done=set()
    for key,g in seen.items():
        if set(g)=={"P","N"} and g["P"].name not in done:
            done.add(g["P"].name); geom=fab.diff.get(g["P"].disc)
            if g["P"].name[:-2]!=g["N"].name[:-2] or not g["P"].name.endswith("_P"): W.append(f"pair {g['P'].name}/{g['N'].name}: names will not auto-pair in KiCad")
            pairs.append(Pair(g["P"].name[:-2],g["P"].name,g["N"].name,g["P"].disc,geom,*fab.limits(g["P"].name[:-2])))
    for disc in sorted({p.disc for p in pairs}):
        if disc not in fab.diff: W.append(f"fab '{fab.name}': no impedance geometry for '{disc}' pairs - get width/gap for the target impedance from the fab's calculator")
    if not fab.verified: W.append(f"fab '{fab.name}': capabilities not yet confirmed against the fab's published rules")
    return rails,pairs

def show_constraints(rails,pairs,fab):
    print(f"-- layout constraints for {fab.name}: {fab.layers} layers, {fab.thickness}, {fab.cu_outer_oz} oz outer, dT {fab.dT}")
    for r in sorted(rails,key=lambda r:-float(r.I)):
        print(f"  rail {r.net:12s} {str(r.I):>8s} -> " + (f"PLANE/ZONE required (a trace would need {r.width})" if r.plane else f"min width {r.width}"))
    by={}
    for p in pairs: by.setdefault(p.disc,[]).append(p)
    for disc,ps in by.items():
        g=ps[0].geom; geo=f"width {g[0]} gap {g[1]} for {g[2]}" if g else "geometry: MISSING"
        print(f"  {len(ps)} {disc} pairs: skew <= {fab.skew}, vias <= {fab.hs_max_vias}, layers {list(fab.hs_layers)}, {geo}")

def emit_dru(rails,pairs,fab):
    """KiCad custom design rules (.kicad_dru). KiCad then enforces the spec live while you route."""
    mmf=lambda q:f"{float(q)*1e3:.3f}mm"
    out=["(version 1)",f"# generated by netspec for {fab.name} - do not edit by hand"]
    for r in rails:
        if not r.plane: out.append(f'(rule "rail {r.net} carries {r.I}"\n  (condition "A.NetName == \'{r.net}\'")\n  (constraint track_width (min {mmf(r.width)})))')
    # skew is a rule per pair: KiCad measures skew across every net a rule matches, so one rule for all pairs would
    # compare lanes with each other. Via limits group by their value.
    for pr in pairs:
        out.append(f'(rule "{pr.name} skew"\n  (condition "A.NetName == \'{pr.p}\' || A.NetName == \'{pr.n}\'")\n  (constraint skew (max {mmf(fab.skew)})))')
    for lim in sorted({p.max_vias for p in pairs}):
        names=" || ".join(f"A.NetName == '{x}'" for p in pairs if p.max_vias==lim for x in (p.p,p.n))
        out.append(f'(rule "pairs with at most {lim} vias"\n  (condition "{names}")\n  (constraint via_count (max {lim})))')
    for disc in sorted({p.disc for p in pairs}):
        names=" || ".join(f"A.NetName == '{x}'" for p in pairs if p.disc==disc for x in (p.p,p.n)); g=fab.diff.get(disc)
        if g:
            out.append(f'(rule "{disc} geometry {g[2]}"\n  (condition "{names}")\n  (constraint track_width (min {mmf(g[0])}) (opt {mmf(g[0])}) (max {mmf(g[0])}))\n  (constraint diff_pair_gap (min {mmf(g[1])}) (opt {mmf(g[1])}) (max {mmf(g[1])})))')
    return "\n".join(out)+"\n"
